const std = @import("std");
const framework = @import("framework");
const services = @import("../domain/services.zig");

pub const MODULE_NAME = "commands";

pub const app_meta = @import("app_meta.zig");
pub const agent_run = @import("agent_run.zig");
pub const agent_stream = @import("agent_stream.zig");
pub const config_get = @import("config_get.zig");
pub const config_set = @import("config_set.zig");
pub const config_migrate_preview = @import("config_migrate_preview.zig");
pub const config_migrate_apply = @import("config_migrate_apply.zig");
pub const config_compat_import = @import("config_compat_import.zig");
pub const diagnostics_summary = @import("diagnostics_summary.zig");
pub const diagnostics_doctor = @import("diagnostics_doctor.zig");
pub const events_poll = @import("events_poll.zig");
pub const events_subscribe = @import("events_subscribe.zig");
pub const gateway_status = @import("gateway_status.zig");
pub const service_status = @import("service_status.zig");
pub const metrics_summary = @import("metrics_summary.zig");
pub const observer_recent = @import("observer_recent.zig");
pub const memory_summary = @import("memory_summary.zig");
pub const session_get = @import("session_get.zig");
pub const session_compact = @import("session_compact.zig");
pub const memory_snapshot_export = @import("memory_snapshot_export.zig");
pub const memory_retrieve = @import("memory_retrieve.zig");
pub const memory_migrate_preview = @import("memory_migrate_preview.zig");
pub const memory_migrate_apply = @import("memory_migrate_apply.zig");
pub const skills_list = @import("skills_list.zig");
pub const skills_install = @import("skills_install.zig");
pub const skills_run = @import("skills_run.zig");
pub const cron_list = @import("cron_list.zig");
pub const cron_register = @import("cron_register.zig");
pub const cron_tick = @import("cron_tick.zig");
pub const heartbeat_status = @import("heartbeat_status.zig");
pub const tunnel_status = @import("tunnel_status.zig");
pub const tunnel_activate = @import("tunnel_activate.zig");
pub const tunnel_deactivate = @import("tunnel_deactivate.zig");
pub const mcp_list = @import("mcp_list.zig");
pub const mcp_register = @import("mcp_register.zig");
pub const hardware_list = @import("hardware_list.zig");
pub const hardware_register = @import("hardware_register.zig");
pub const peripheral_register = @import("peripheral_register.zig");
pub const gateway_start = @import("gateway_start.zig");
pub const gateway_stop = @import("gateway_stop.zig");
pub const gateway_reload = @import("gateway_reload.zig");
pub const gateway_stream_subscribe = @import("gateway_stream_subscribe.zig");
pub const service_install = @import("service_install.zig");
pub const service_start = @import("service_start.zig");
pub const service_stop = @import("service_stop.zig");
pub const service_restart = @import("service_restart.zig");
pub const logs_recent = @import("logs_recent.zig");
pub const task_get = @import("task_get.zig");
pub const task_by_request = @import("task_by_request.zig");

pub fn registerBuiltins(registry: *framework.CommandRegistry, command_services: *services.CommandServices) anyerror!void {
    try registry.register(app_meta.definition(command_services));
    try registry.register(agent_run.definition(command_services));
    try registry.register(agent_stream.definition(command_services));
    try registry.register(config_get.definition(command_services));
    try registry.register(config_set.definition(command_services));
    try registry.register(config_migrate_preview.definition(command_services));
    try registry.register(config_migrate_apply.definition(command_services));
    try registry.register(config_compat_import.definition(command_services));
    try registry.register(diagnostics_summary.definition(command_services));
    try registry.register(diagnostics_doctor.definition(command_services));
    try registry.register(events_poll.definition(command_services));
    try registry.register(events_subscribe.definition(command_services));
    try registry.register(gateway_status.definition(command_services));
    try registry.register(gateway_start.definition(command_services));
    try registry.register(gateway_stop.definition(command_services));
    try registry.register(gateway_reload.definition(command_services));
    try registry.register(gateway_stream_subscribe.definition(command_services));
    try registry.register(service_status.definition(command_services));
    try registry.register(service_install.definition(command_services));
    try registry.register(service_start.definition(command_services));
    try registry.register(service_stop.definition(command_services));
    try registry.register(service_restart.definition(command_services));
    try registry.register(metrics_summary.definition(command_services));
    try registry.register(observer_recent.definition(command_services));
    try registry.register(memory_summary.definition(command_services));
    try registry.register(session_get.definition(command_services));
    try registry.register(session_compact.definition(command_services));
    try registry.register(memory_snapshot_export.definition(command_services));
    try registry.register(memory_retrieve.definition(command_services));
    try registry.register(memory_migrate_preview.definition(command_services));
    try registry.register(memory_migrate_apply.definition(command_services));
    try registry.register(skills_list.definition(command_services));
    try registry.register(skills_install.definition(command_services));
    try registry.register(skills_run.definition(command_services));
    try registry.register(cron_list.definition(command_services));
    try registry.register(cron_register.definition(command_services));
    try registry.register(cron_tick.definition(command_services));
    try registry.register(heartbeat_status.definition(command_services));
    try registry.register(tunnel_status.definition(command_services));
    try registry.register(tunnel_activate.definition(command_services));
    try registry.register(tunnel_deactivate.definition(command_services));
    try registry.register(mcp_list.definition(command_services));
    try registry.register(mcp_register.definition(command_services));
    try registry.register(hardware_list.definition(command_services));
    try registry.register(hardware_register.definition(command_services));
    try registry.register(peripheral_register.definition(command_services));
    try registry.register(logs_recent.definition(command_services));
    try registry.register(task_get.definition(command_services));
    try registry.register(task_by_request.definition(command_services));
}

test "commands exports are stable" {
    try std.testing.expectEqualStrings("commands", MODULE_NAME);
}
