const std = @import("std");
const framework = @import("framework");
const domain = @import("../domain/root.zig");
const services = domain.services;

pub const MODULE_NAME = "commands";

pub const app_meta = @import("status/app_meta.zig");
pub const status_all = @import("status/status_all.zig");
pub const agent_run = @import("agent/agent_run.zig");
pub const agent_stream = @import("agent/agent_stream.zig");
pub const config_get = @import("config/config_get.zig");
pub const config_set = @import("config/config_set.zig");
pub const config_migrate_preview = @import("config/config_migrate_preview.zig");
pub const config_migrate_apply = @import("config/config_migrate_apply.zig");
pub const config_compat_import = @import("config/config_compat_import.zig");
pub const diagnostics_summary = @import("diagnostics/diagnostics_summary.zig");
pub const diagnostics_doctor = @import("diagnostics/diagnostics_doctor.zig");
pub const diagnostics_remediate_preview = @import("diagnostics/diagnostics_remediate_preview.zig");
pub const diagnostics_remediate_apply = @import("diagnostics/diagnostics_remediate_apply.zig");
pub const onboard_summary = @import("onboard/onboard_summary.zig");
pub const onboard_apply_defaults = @import("onboard/onboard_apply_defaults.zig");
pub const device_pair_list = @import("device/device_pair_list.zig");
pub const device_pair_request = @import("device/device_pair_request.zig");
pub const device_pair_approve = @import("device/device_pair_approve.zig");
pub const device_pair_reject = @import("device/device_pair_reject.zig");
pub const device_unpair = @import("device/device_unpair.zig");
pub const device_token_rotate = @import("device/device_token_rotate.zig");
pub const device_token_revoke = @import("device/device_token_revoke.zig");
pub const devices_list = @import("device/devices_list.zig");
pub const node_list = @import("device/node_list.zig");
pub const node_describe = @import("device/node_describe.zig");
pub const node_invoke = @import("device/node_invoke.zig");
pub const events_poll = @import("events/events_poll.zig");
pub const events_subscribe = @import("events/events_subscribe.zig");
pub const gateway_status = @import("gateway/gateway_status.zig");
pub const gateway_auth_status = @import("gateway/gateway_auth_status.zig");
pub const gateway_token_status = @import("gateway/gateway_token_status.zig");
pub const gateway_token_generate = @import("gateway/gateway_token_generate.zig");
pub const gateway_token_rotate = @import("gateway/gateway_token_rotate.zig");
pub const gateway_token_revoke = @import("gateway/gateway_token_revoke.zig");
pub const gateway_password_status = @import("gateway/gateway_password_status.zig");
pub const gateway_password_set = @import("gateway/gateway_password_set.zig");
pub const gateway_password_clear = @import("gateway/gateway_password_clear.zig");
pub const gateway_access_link = @import("gateway/gateway_access_link.zig");
pub const gateway_remote_status = @import("gateway/gateway_remote_status.zig");
pub const gateway_remote_enable = @import("gateway/gateway_remote_enable.zig");
pub const gateway_remote_disable = @import("gateway/gateway_remote_disable.zig");
pub const gateway_remote_policy_status = @import("gateway/gateway_remote_policy_status.zig");
pub const gateway_remote_policy_set = @import("gateway/gateway_remote_policy_set.zig");
pub const service_status = @import("service/service_status.zig");
pub const metrics_summary = @import("system/metrics_summary.zig");
pub const observer_recent = @import("system/observer_recent.zig");
pub const memory_summary = @import("memory/memory_summary.zig");
pub const session_get = @import("session/session_get.zig");
pub const session_compact = @import("session/session_compact.zig");
pub const memory_snapshot_export = @import("memory/memory_snapshot_export.zig");
pub const memory_snapshot_import = @import("memory/memory_snapshot_import.zig");
pub const memory_retrieve = @import("memory/memory_retrieve.zig");
pub const memory_migrate_preview = @import("memory/memory_migrate_preview.zig");
pub const memory_migrate_apply = @import("memory/memory_migrate_apply.zig");
pub const skills_list = @import("skills/skills_list.zig");
pub const skills_install = @import("skills/skills_install.zig");
pub const skills_run = @import("skills/skills_run.zig");
pub const cron_list = @import("system/cron_list.zig");
pub const cron_register = @import("system/cron_register.zig");
pub const cron_tick = @import("system/cron_tick.zig");
pub const heartbeat_status = @import("system/heartbeat_status.zig");
pub const tunnel_status = @import("system/tunnel_status.zig");
pub const tunnel_activate = @import("system/tunnel_activate.zig");
pub const tunnel_deactivate = @import("system/tunnel_deactivate.zig");
pub const mcp_list = @import("system/mcp_list.zig");
pub const mcp_register = @import("system/mcp_register.zig");
pub const hardware_list = @import("system/hardware_list.zig");
pub const hardware_register = @import("system/hardware_register.zig");
pub const peripheral_register = @import("system/peripheral_register.zig");
pub const voice_status = @import("system/voice_status.zig");
pub const voice_attach = @import("system/voice_attach.zig");
pub const voice_detach = @import("system/voice_detach.zig");
pub const gateway_start = @import("gateway/gateway_start.zig");
pub const gateway_stop = @import("gateway/gateway_stop.zig");
pub const gateway_reload = @import("gateway/gateway_reload.zig");
pub const gateway_stream_subscribe = @import("gateway/gateway_stream_subscribe.zig");
pub const service_install = @import("service/service_install.zig");
pub const service_start = @import("service/service_start.zig");
pub const service_stop = @import("service/service_stop.zig");
pub const service_restart = @import("service/service_restart.zig");
pub const logs_recent = @import("system/logs_recent.zig");
pub const task_get = @import("tasks/task_get.zig");
pub const task_by_request = @import("tasks/task_by_request.zig");
pub const channels_status = @import("status/channels_status.zig");
pub const providers_status = @import("status/providers_status.zig");

pub fn registerBuiltins(registry: *framework.CommandRegistry, command_services: *services.CommandServices) anyerror!void {
    try registry.register(app_meta.definition(command_services));
    try registry.register(status_all.definition(command_services));
    try registry.register(agent_run.definition(command_services));
    try registry.register(agent_stream.definition(command_services));
    try registry.register(config_get.definition(command_services));
    try registry.register(config_set.definition(command_services));
    try registry.register(config_migrate_preview.definition(command_services));
    try registry.register(config_migrate_apply.definition(command_services));
    try registry.register(config_compat_import.definition(command_services));
    try registry.register(diagnostics_summary.definition(command_services));
    try registry.register(diagnostics_doctor.definition(command_services));
    try registry.register(diagnostics_remediate_preview.definition(command_services));
    try registry.register(diagnostics_remediate_apply.definition(command_services));
    try registry.register(onboard_summary.definition(command_services));
    try registry.register(onboard_apply_defaults.definition(command_services));
    try registry.register(device_pair_list.definition(command_services));
    try registry.register(device_pair_request.definition(command_services));
    try registry.register(device_pair_approve.definition(command_services));
    try registry.register(device_pair_reject.definition(command_services));
    try registry.register(device_unpair.definition(command_services));
    try registry.register(device_token_rotate.definition(command_services));
    try registry.register(device_token_revoke.definition(command_services));
    try registry.register(devices_list.definition(command_services));
    try registry.register(node_list.definition(command_services));
    try registry.register(node_describe.definition(command_services));
    try registry.register(node_invoke.definition(command_services));
    try registry.register(events_poll.definition(command_services));
    try registry.register(events_subscribe.definition(command_services));
    try registry.register(gateway_status.definition(command_services));
    try registry.register(gateway_auth_status.definition(command_services));
    try registry.register(gateway_token_status.definition(command_services));
    try registry.register(gateway_token_generate.definition(command_services));
    try registry.register(gateway_token_rotate.definition(command_services));
    try registry.register(gateway_token_revoke.definition(command_services));
    try registry.register(gateway_password_status.definition(command_services));
    try registry.register(gateway_password_set.definition(command_services));
    try registry.register(gateway_password_clear.definition(command_services));
    try registry.register(gateway_access_link.definition(command_services));
    try registry.register(gateway_remote_status.definition(command_services));
    try registry.register(gateway_remote_enable.definition(command_services));
    try registry.register(gateway_remote_disable.definition(command_services));
    try registry.register(gateway_remote_policy_status.definition(command_services));
    try registry.register(gateway_remote_policy_set.definition(command_services));
    try registry.register(gateway_start.definition(command_services));
    try registry.register(gateway_stop.definition(command_services));
    try registry.register(gateway_reload.definition(command_services));
    try registry.register(gateway_stream_subscribe.definition(command_services));
    try registry.register(service_status.definition(command_services));
    try registry.register(service_install.definition(command_services));
    try registry.register(service_start.definition(command_services));
    try registry.register(service_stop.definition(command_services));
    try registry.register(service_restart.definition(command_services));
    try registry.register(metrics_summary.definition(command_services));
    try registry.register(observer_recent.definition(command_services));
    try registry.register(memory_summary.definition(command_services));
    try registry.register(session_get.definition(command_services));
    try registry.register(session_compact.definition(command_services));
    try registry.register(memory_snapshot_export.definition(command_services));
    try registry.register(memory_snapshot_import.definition(command_services));
    try registry.register(memory_retrieve.definition(command_services));
    try registry.register(memory_migrate_preview.definition(command_services));
    try registry.register(memory_migrate_apply.definition(command_services));
    try registry.register(skills_list.definition(command_services));
    try registry.register(skills_install.definition(command_services));
    try registry.register(skills_run.definition(command_services));
    try registry.register(cron_list.definition(command_services));
    try registry.register(cron_register.definition(command_services));
    try registry.register(cron_tick.definition(command_services));
    try registry.register(heartbeat_status.definition(command_services));
    try registry.register(tunnel_status.definition(command_services));
    try registry.register(tunnel_activate.definition(command_services));
    try registry.register(tunnel_deactivate.definition(command_services));
    try registry.register(mcp_list.definition(command_services));
    try registry.register(mcp_register.definition(command_services));
    try registry.register(hardware_list.definition(command_services));
    try registry.register(hardware_register.definition(command_services));
    try registry.register(peripheral_register.definition(command_services));
    try registry.register(voice_status.definition(command_services));
    try registry.register(voice_attach.definition(command_services));
    try registry.register(voice_detach.definition(command_services));
    try registry.register(logs_recent.definition(command_services));
    try registry.register(task_get.definition(command_services));
    try registry.register(task_by_request.definition(command_services));
    try registry.register(channels_status.definition(command_services));
    try registry.register(providers_status.definition(command_services));
}

test "commands exports are stable" {
    try std.testing.expectEqualStrings("commands", MODULE_NAME);
}
